name: Sync Notion to GitHub

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv notion-client beautifulsoup4

    - name: Sync Notion to HTML
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        python sync_notion.py

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add *.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-sync from Notion" && git push)
