name: Sync Notion to Cloudflare Pages

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv notion-client beautifulsoup4

      - name: Debug Environment Variables
        run: |
          echo "NOTION_RESOURCE_ID length: ${#NOTION_RESOURCE_ID}"
          echo "NOTION_RESOURCE_ID first 5 chars: ${NOTION_RESOURCE_ID:0:5}"
        env:
          NOTION_RESOURCE_ID: ${{ secrets.NOTION_RESOURCE_ID }}

      - name: Sync Notion to HTML
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_RESOURCE_ID: ${{ secrets.NOTION_RESOURCE_ID }}
        run: |
          python sync_notion.py

      - name: Check if index.html exists
        run: |
          if [ ! -f "index.html" ]; then
            echo "index.html not found!"
            cat sync_notion.log  # Вывод лога, если файл не создан
            exit 1
          fi

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PROJECT }}/deployments" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -F "file=@./index.html"
