name: Sync Notion Page to Cloudflare Pages

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown2 jinja2

      - name: Fetch Notion page content
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_PAGE_IDS: ${{ secrets.NOTION_PAGE_IDS }}
        run: python sync_notion.py

      - name: Check for generated files
        run: |
          if [ ! -f "index.html" ]; then
            echo "index.html not found!"
            exit 1
          fi
          if [ ! -f "template.html" ]; then
            echo "template.html not found!"
            exit 1
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT }}
          directory: build
          gitHubToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
