name: Sync Public Notion Page to Cloudflare Pages

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Sync Notion to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT: ${{ secrets.CLOUDFLARE_PROJECT }}
        run: |
          python sync_notion.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloudflare-deployment-logs
          path: cloudflare-deployment.log
        if: always()

      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: Sync to Cloudflare Pages failed!
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}  # Убедитесь, что у вас есть этот секрет, если вы хотите использовать Slack для уведомлений
