name: Sync Public Notion Page to Cloudflare Pages

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Sync Notion to HTML
        run: |
          python sync_notion.py

      - name: Check if index.html exists
        run: |
          if [ ! -f "index.html" ]; then
            echo "index.html not found!"
            exit 1
          fi

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT: ${{ secrets.CLOUDFLARE_PROJECT }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$CLOUDFLARE_PROJECT/deployments" \
          -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
          -F "file=@./index.html"
